name: PythonExt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Deps
      run: |
           sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
           sudo apt-get update
           sudo apt install -y ninja-build
           sudo apt install -y gcc-11 g++-11
           sudo apt install -y libglfw3-dev libglew-dev libglm-dev
           sudo apt install -y libpython3-dev

    - name: Build Python modules
      run: |
           mkdir build-release
           cd discord
           python setup.py build
      env:
        CC: gcc-11
        CXX: g++-11

    - name: Run Tests
      run: |
           cd discord
           python test.py 

      
